import SkillBadge from '@/components/Badge/SkillBadge';

export const SkillBadges = [
    <SkillBadge key="react" name="1" label="react" logoSize={32} />,
    <SkillBadge key="javascript" name="2" label="javascript" logoSize={32} />,
    <SkillBadge key="next" name="3" label="next" logoSize={32} />,
    <SkillBadge key="django" name="4" label="django" logoSize={32} />,
    <SkillBadge key="express" name="5" label="express" logoSize={32} />,
    <SkillBadge key="firebase" name="6" label="firebase" logoSize={32} />,
    <SkillBadge key="flutter" name="7" label="flutter" logoSize={32} />,
    <SkillBadge key="go" name="8" label="go" logoSize={32} />,
    <SkillBadge key="graphql" name="9" label="graphql" logoSize={32} />,
    <SkillBadge key="kotlin" name="10" label="kotlin" logoSize={32} />,
    <SkillBadge key="mongodb" name="11" label="mongodb" logoSize={32} />,
    <SkillBadge key="mysql" name="12" label="mysql" logoSize={32} />,
    <SkillBadge key="nest" name="13" label="nest" logoSize={32} />,
    <SkillBadge key="node" name="14" label="node" logoSize={32} />,
    <SkillBadge key="php" name="15" label="php" logoSize={32} />,
    <SkillBadge key="python" name="16" label="python" logoSize={32} />,
    <SkillBadge key="spring" name="17" label="spring" logoSize={32} />,
    <SkillBadge key="swift" name="18" label="swift" logoSize={32} />,
    <SkillBadge key="typescript" name="19" label="typescript" logoSize={32} />,
    <SkillBadge key="unity" name="20" label="unity" logoSize={32} />,
    <SkillBadge key="vue" name="21" label="vue" logoSize={32} />,
];
